
name: Build

on:
  push:
    tags:
    - '*'

jobs:

  build-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          sudo apt-get update
          sudo apt-get install build-essential fakeroot dh-make git cmake dpkg-dev
          sudo apt-get install qtdeclarative5-dev qtbase5-dev qttools5-dev qttools5-dev-tools qttranslations5-l10n
          sudo apt-get install qttools5-dev
          # TODO must be not root, but else we have error
          sudo dpkg-buildpackage -rfakeroot -b --no-sign
          file_name_orig=$(ls ../ | grep "passcopier_"| grep ".deb")
          file_name=$(echo $file_name_orig | sed -E 's/^([a-z|0-9-]*)_([0-9|\.]*)(.*)$/\1_\2_20.04\3/g')
          release_name=$(echo $file_name_orig | sed -E 's/^([a-z|0-9-]*)_([0-9|\.]*)(.*)$/\1 \2/g')
          sudo mv ../$file_name_orig ../$file_name
          asset_path="../"$file_name
          asset_name=$release_name
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=asset_name::${asset_name}"
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.8
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: ${{ steps.build.outputs.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          sudo apt-get update
          sudo apt-get install build-essential fakeroot dh-make git cmake dpkg-dev
          sudo apt-get install qtdeclarative5-dev qtbase5-dev qttools5-dev qttools5-dev-tools qttranslations5-l10n
          sudo apt-get install qttools5-dev
          dpkg-buildpackage -rfakeroot -b --no-sign
          file_name_orig=$(ls ../ | grep "passcopier_"| grep ".deb")
          file_name=$(echo $file_name_orig | sed -E 's/^([a-z|0-9-]*)_([0-9|\.]*)(.*)$/\1_\2_18.04\3/g')
          release_name=$(echo $file_name_orig | sed -E 's/^([a-z|0-9-]*)_([0-9|\.]*)(.*)$/\1 \2/g')
          mv ../$file_name_orig ../$file_name
          asset_path="../"$file_name
          asset_name=$release_name
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=asset_name::${asset_name}"
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.8
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: ${{ steps.build.outputs.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

